version: "3"

services:
  api:
    container_name: linkconverter_api
    restart: "always"
    build:
      context: .
    ports:
      - "2626:2626"
    links:
      - db
  db:
    container_name: linkconventer_mysql_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_database: linkconverter_mysql
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mahmut/
