// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "linkconverter-api/models"

// DbBuilderInterface is an autogenerated mock type for the DbBuilderInterface type
type DbBuilderInterface struct {
	mock.Mock
}

// DbConnection provides a mock function with given fields:
func (_m *DbBuilderInterface) DbConnection() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertLogEvent provides a mock function with given fields: logEvent
func (_m *DbBuilderInterface) InsertLogEvent(logEvent models.LogEventModel) error {
	ret := _m.Called(logEvent)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.LogEventModel) error); ok {
		r0 = rf(logEvent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
