// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "linkconverter-api/models"

// UrlParserInterface is an autogenerated mock type for the UrlParserInterface type
type UrlParserInterface struct {
	mock.Mock
}

// Parse provides a mock function with given fields: url
func (_m *UrlParserInterface) Parse(url string) (models.ParsedUrlModel, error) {
	ret := _m.Called(url)

	var r0 models.ParsedUrlModel
	if rf, ok := ret.Get(0).(func(string) models.ParsedUrlModel); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(models.ParsedUrlModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
