// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import echo "github.com/labstack/echo/v4"
import mock "github.com/stretchr/testify/mock"

// UrlToDeepRouterInterface is an autogenerated mock type for the UrlToDeepRouterInterface type
type UrlToDeepRouterInterface struct {
	mock.Mock
}

// UrlToDeep provides a mock function with given fields: context
func (_m *UrlToDeepRouterInterface) UrlToDeep(context echo.Context) error {
	ret := _m.Called(context)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
